#!/usr/bin/env bash
# Exit on error
set -e
if [ $# -lt 1 ]; then
    dnames="alpineproc ubuntuproc/14.04 ubuntuproc"
    echo "Checking Dockerfile heads ... ..."
    for dname in $dnames; do
        grep FROM $dname/Dockerfile
    done
    echo "... Pausing 5 seconds ..."
    sleep 5
else
    dnames=$@
fi
orgname="mubiic"
basedir=$(pwd)
tagname=""
latestlist="3.2 14.04"
dockerfile="Dockerfile"

if [ -f "$basedir/localbuild" ]; then
    for dname in $dnames; do
       if [ -d "${basedir}/${dname}" ]; then
            cd "${basedir}/${dname}"
            [ -f "./sync" ] && ./sync
            ##[ -f "./prebuild" ] && ./prebuild && ./prebuild 15.04
            echo "Please run prebuild manually and upload the ubuntucore to the hub."
            echo
            if [ -f "./${dockerfile}" ]; then
               dname="$(echo $dname | cut -d/ -f1)"
               tagname="$(cat ./${dockerfile} | awk -F':' '/FROM .*/{print $2}')"
               if [ -n "$tagname" ]; then
                    echo " ... ...... ... Start building ${orgname}/${dname}:${tagname} ... ...... ... " >&2
                    docker build --force-rm -t "${orgname}/${dname}:${tagname}" .
                    if [ -n "$(echo $latestlist | grep $tagname)" ]; then
                        echo " ... ...... ... Tagging ${orgname}/${dname}:${tagname} as latest ... ...... ... " >&2
                        docker tag -f "${orgname}/${dname}:${tagname}" "${orgname}/${dname}:latest"
                    fi
                    echo " ... ...... ... Finish building ${orgname}/${dname}:${tagname} ... ...... ... " >&2
               else
                    echo "... ... ... ... Start building ${orgname}/${dname} ... ...... ... " >&2
                    docker build --force-rm -t "${orgname}/${dname}" .
                    echo "... ... ... ... Finish building ${orgname}/${dname} ... ... ... ... " >&2
               fi
            else
                echo "Cannot find the dockerfile: ${basedir}/${dname}/${dockerfile}"
            fi
       else
        echo "Cannot find the directory: ${basedir}/${dname}"
       fi
       cd "${basedir}"
    done
    exit 0
else
    echo "Please run localbuild.sh in its holding directory."
    exit 1
fi
